# This workflow will build a .NET Core project
name: .NET Core CI/CD

on: 
  push:
    branches: 
    # Run the workflow when pushing to the specific branch
    -  master
    -  develop
  pull_request:
    branches:
    # Run the workflow when pull requests in the specific branch
    -  master
    -  develop
  # Allow running the workflow manually from the GitHub UI
  workflow_dispatch:
# Cancel a currently running workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checks out the source code at the latest commit
    - uses: actions/checkout@v3
    # Installs the .NET SDK on the build machine
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Check default dotnet version
      run: dotnet --version
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget
        restore-keys: |
          ${{ runner.os }}-nuget
    # Installs any NuGet packages required.
    - name: Install dependencies
      run: dotnet restore
    # Builds the project
    - name: Build
      run: dotnet build --configuration Release --no-restore
    # Runs any tests in the project
    - name: Test
      run: dotnet test --no-build --verbosity normal
    # Publish the project
    - name: Publish 
      run: dotnet publish -c Release /p:WebPublishMethod=Package /p:PackageLocation="${{github.workspace}}\website" #-o ${{github.workspace}}\website 

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: publish
        path: ${{github.workspace}}\website

  deploy:
    env:
      SITE_NAME: mitac

    permissions:
      contents: none
    runs-on: self-hosted
    needs: build
    environment:
      name: 'Development'

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: publish
        path: ${{github.workspace}}\website
        
    - name: Local IIS Deploy
      uses: cschleiden/webdeploy-action@v1.1.0
      with:
        # Name of an existing website on the IIS machine
        webSiteName: 'https://localhost'
        # File path to the package or a folder generated by MSBuild or a compressed archive file.
        package: ${{github.workspace}}\website
        # (Optional) Select the option to delete files on the Web App that have no matching files in the Web App zip package.
        removeAdditionalFilesFlag: false # optional
        # (Optional) Select the option to take the Web App offline by placing an app_offline.htm file in the root directory of the Web App before the sync operation begins. The file will be removed after the sync operation completes successfully.
        takeAppOfflineFlag: '' # optional
      
      

