# This workflow will build a .NET Core project
name: .NET Core CI/CD
on: 
  push:
    branches: 
    # Run the workflow when pushing to the specific branch
    -  master
    -  develop
  pull_request:
    branches:
    # Run the workflow when pull requests in the specific branch
    -  master
    -  develop
  # Allow running the workflow manually from the GitHub UI
  workflow_dispatch:
# Cancel a currently running workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checks out the source code at the latest commit
    - uses: actions/checkout@v3
    # Installs the .NET SDK on the build machine
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Check default dotnet version
      run: dotnet --version
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget
        restore-keys: |
          ${{ runner.os }}-nuget
    # Installs any NuGet packages required.
    - name: Install dependencies
      run: dotnet restore
    # Builds the project
    - name: Build
      run: dotnet build --configuration Release --no-restore
    # Runs any tests in the project
    - name: Test
      run: dotnet test --no-build --verbosity normal

  deploy:
    permissions:
      contents: none
    runs-on: self-hosted
    needs: build
    environment:
      name: 'Development'

    steps:
    - name: IIS Deploy
      uses: ChristopheLav/iis-deploy@v1.0.0
      #with:
        # IIS website name
        #website-name: 
        # MS Deploy Service URL
        #msdeploy-service-url: 
        # Username used by Basic authentication to the MS Deploy Service
        #msdeploy-username: 
        # Password used by Basic authentication to the MS Deploy Service
        #msdeploy-password: 
        # The path to the source directory that will be deployed
        #source-path: 
